### ISSUE TITLE
Add explicit license

### ISSUE THREAD

**Issue by Arithmomaniac** [mgibas/avatarator#1]
Is this free for commercial use? Under what terms? Please attach a license. Thanks :-)

**Comment by mgibas** [comment]
It's as free as it can get :) isn't it a default when there is no license ?

**Comment by Arithmomaniac** [comment]
[No](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license). May I suggest the [MIT License](http://choosealicense.com/licenses/mit/)?

**Comment by mgibas** [comment]
Oo nice to know :) Will update it today evening. Thanks

**Comment by mgibas** [comment]
MIT license added
